---
- name: Install Apache
  hosts: your_server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Apache packages
      apt:
        name: apache2
        state: present
      become: yes

    - name: Enable Apache module
      apache2_module:
        name: rewrite
        state: present
      become: yes

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
      become: yes

